export const countries = [
  'Ägypten',
  'Äquatorialguinea',
  'Äthiopien',
  'Afghanistan',
  'Albanien',
  'Algerien',
  'Andorra',
  'Angola',
  'Antigua und Barbuda',
  'Argentinien',
  'Armenien',
  'Aserbaidschan',
  'Australien',
  'Bahamas',
  'Bahrain',
  'Bangladesch',
  'Barbados',
  'Belarus',
  'Belgien',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivien, Plurinationaler Staat',
  'Bosnien und Herzegowina',
  'Botsuana',
  'Brasilien',
  'Britische Überseegebiete',
  'Brunei Darussalam',
  'Bulgarien',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Chile',
  'China',
  'Costa Rica',
  'Cote d\'Ivoire',
  'Dominica',
  'Dominikanische Republik',
  'Dschibuti',
  'Dänemark',
  'Ecuador',
  'El Salvador',
  'Eritrea',
  'Estland',
  'Eswatini',
  'Fidschi',
  'Finnland',
  'Frankreich',
  'Gabun',
  'Gambia',
  'Georgien',
  'Ghana',
  'Grenada',
  'Griechenland',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hongkong',
  'Indien',
  'Indonesien',
  'Irak',
  'Iran, Islamische Republik',
  'Irland',
  'Island',
  'Israel',
  'Italien',
  'Jamaika',
  'Japan',
  'Jemen',
  'Jordanien',
  'Jugoslawien, Bundesrep. (27.04.1992-04.02.2003)',
  'Jugoslawien, Soz. Föd. Republik (bis 26.04.1992)',
  'Kambodscha',
  'Kamerun',
  'Kanada',
  'Kasachstan',
  'Katar',
  'Kenia',
  'Kirgisistan',
  'Kiribati',
  'Kolumbien',
  'Komoren',
  'Kongo, Demokratische Republik',
  'Kongo, Republik',
  'Korea, Demokratische Volksrepublik',
  'Korea, Republik',
  'Kosovo',
  'Kroatien',
  'Kuba',
  'Kuwait',
  'Laos, Demokratische Volksrepublik',
  'Lesotho',
  'Lettland',
  'Libanon',
  'Liberia',
  'Libyen',
  'Liechtenstein',
  'Litauen',
  'Luxemburg',
  'Macau',
  'Madagaskar',
  'Malawi',
  'Malaysia',
  'Malediven',
  'Mali',
  'Malta',
  'Marokko',
  'Marshallinseln',
  'Mauretanien',
  'Mauritius',
  'Mexiko',
  'Mikronesien, Föderierte Staaten von',
  'Moldau, Republik',
  'Monaco',
  'Mongolei',
  'Montenegro (ab 03.06.2006)',
  'Mosambik',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Neuseeland',
  'Nicaragua',
  'Niederlande',
  'Niger',
  'Nigeria',
  'Nordmazedonien',
  'Norwegen',
  'Österreich',
  'Oman',
  'Pakistan',
  'Palau',
  'Palästinensische Gebiete',
  'Panama',
  'Papua-Neuguinea',
  'Paraguay',
  'Peru',
  'Philippinen',
  'Polen',
  'Portugal',
  'Ruanda',
  'Rumänien',
  'Russische Föderation',
  'Salomonen',
  'Sambia',
  'Samoa',
  'San Marino',
  'Sao Tome und Principe',
  'Saudi-Arabien',
  'Schweden',
  'Schweiz',
  'Senegal',
  'Serbien',
  'Serbien (einschl. Kosovo) (03.06.2006-16.02.2008)',
  'Serbien und Montenegro (05.02.2003-02.06.2006)',
  'Seychellen',
  'Sierra Leone',
  'Simbabwe',
  'Singapur',
  'Slowakei',
  'Slowenien',
  'Somalia',
  'Sowjetunion (bis 25.12.1991)',
  'Spanien',
  'Sri Lanka',
  'St. Kitts und Nevis',
  'St. Lucia',
  'St. Vincent und die Grenadinen',
  'Staatenlos',
  'Sudan (einschließlich Südsudan) (bis 08.07.2011)',
  'Sudan (ohne Südsudan) (ab 09.07.2011)',
  'Suriname',
  'Syrien',
  'Südafrika',
  'Südsudan (ab 09.07.2011)',
  'Tadschikistan',
  'Taiwan',
  'Tansania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad und Tobago',
  'Tschad',
  'Tschechien',
  'Tschechoslowakei (bis 31.12.1992)',
  'Tunesien',
  'Turkmenistan',
  'Tuvalu',
  'Türkei',
  'Uganda',
  'Ukraine',
  'Ungarn',
  'Ungeklärt / Ohne Angabe',
  'Uruguay',
  'Usbekistan',
  'Vanuatu',
  'Vatikanstadt',
  'Venezuela, Bolivarische Republik',
  'Vereinigte Arabische Emirate',
  'Vereinigte Staaten',
  'Vereinigtes Königreich',
  'Vietnam',
  'Zentralafrikanische Republik',
  'Zypern'
]

export const regions = [
    ['Welt',
      ['Afrika', [
          ['Nordafrika', ['Ägypten', 'Algerien', 'Libyen', 'Marokko', 'Sudan (einschließlich Südsudan) (bis 08.07.2011)', 'Sudan (ohne Südsudan) (ab 09.07.2011)', 'Tunesien']],
          ['Westafrika', ['Benin', 'Burkina Faso', 'Cabo Verde', 'Cote d\'Ivoire', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Mauretanien', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo']],
          ['Ostafrika', ['Äthiopien', 'Burundi', 'Dschibuti', 'Eritrea', 'Kenia', 'Komoren', 'Madagaskar', 'Malawi', 'Mauritius', 'Mosambik', 'Ruanda', 'Seychellen', 'Simbabwe', 'Somalia', 'Südsudan (ab 09.07.2011)', 'Tansania', 'Uganda']],
          ['Zentralafrika', ['Angola', 'Äquatorialguinea', 'Gabun', 'Kamerun', 'Kongo, Demokratische Republik', 'Kongo, Republik', 'Sambia', 'Sao Tome und Principe', 'Tschad', 'Zentralafrikanische Republik']],
          ['Südafrika', ['Botsuana', 'Eswatini', 'Lesotho', 'Namibia', 'Südafrika']]
      ]],
      ['Amerika', [
          ['Nordamerika', ['Kanada', 'Vereinigte Staaten']],
          ['Zentralamerika', ['Belize', 'Costa Rica', 'El Salvador', 'Guatemala', 'Honduras', 'Mexiko', 'Nicaragua', 'Panama']],
          ['Karibik', ['Antigua und Barbuda', 'Bahamas', 'Barbados', 'Dominica', 'Dominikanische Republik', 'Grenada', 'Haiti', 'Jamaika', 'Kuba', 'St. Kitts und Nevis', 'St. Lucia', 'St. Vincent und die Grenadinen', 'Trinidad und Tobago']],
          ['Südamerika', ['Argentinien', 'Bolivien, Plurinationaler Staat', 'Brasilien', 'Chile', 'Ecuador', 'Guyana', 'Kolumbien', 'Paraquay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela, Bolivarische Republik']]
      ]],
      ['Asien', [
          ['Westasien', ['Armenien', 'Aserbaidschan', 'Bahrain', 'Georgien', 'Irak', 'Israel', 'Jemen', 'Jordanien', 'Katar', 'Kuwait', 'Libanon', 'Oman', 'Palästinensische Gebiete', 'Saudi-Arabien', 'Syrien', 'Türkei', 'Vereinigte Arabische Emirate', 'Zypern']],
          ['Zentralasien', ['Kasachstan', 'Kirgisistan', 'Tadschikistan', 'Turkmenistan', 'Usbekistan']],
          ['Ostasien', ['China', 'Hongkong', 'Japan', 'Korea, Demokratische Volksrepublik', 'Korea, Republik', 'Macau', 'Mongolei', 'Taiwan']],
          ['Südasien', ['Afghanistan', 'Bangladesch', 'Bhutan', 'Indien', 'Iran, Islamische Republik', 'Malediven', 'Nepal', 'Pakistan', 'Sri Lanka']],
          ['Südostasien', ['Brunei Darussalam', 'Indonesien', 'Kambodscha', 'Laos, Demokratische Volksrepublik', 'Malaysia', 'Myanmar', 'Philippinen', 'Singapur', 'Thailand', 'Timor-Leste', 'Vietnam']]
      ]],
      ['Europa', [
          ['Nordeuropa', ['Dänemark', 'Estland', 'Finnland', 'Irland', 'Island', 'Lettland', 'Litauen', 'Norwegen', 'Schweden', 'Vereinigtes Königreich']],
          ['Westeuropa', ['Belgien', 'Frankreich', 'Liechtenstein', 'Luxemburg', 'Monaco', 'Niederlande', 'Österreich', 'Schweiz']],
          ['Osteuropa', ['Belarus', 'Bulgarien', 'Moldau, Republik', 'Polen', 'Rumänien', 'Russische Föderation', 'Slowakei', 'Sowjetunion (bis 25.12.1991)', 'Tschechien', 'Tschechoslowakei (bis 31.12.1992)', 'Ukraine', 'Ungarn']],
          ['Südeuropa', ['Albanien', 'Andorra', 'Bosnien und Herzegowina', 'Griechenland', 'Italien', 'Jugoslawien, Bundesrep. (27.04.1992-04.02.2003)', 'Jugoslawien, Soz. Föd. Republik (bis 26.04.1992)', 'Kosovo', 'Kroatien', 'Malta', 'Montenegro (ab 03.06.2006)', 'Nordmazedonien', 'Portugal', 'San Marino', 'Serbien', 'Serbien (einschl. Kosovo) (03.06.2006-16.02.2008)', 'Serbien und Montenegro (05.02.2003-02.06.2006)', 'Slowenien', 'Spanien', 'Vatikanstadt']]
      ]],
      ['Ozeanien', [
          ['Australien und Neuseeland', ['Australien', 'Neuseeland']],
          ['Melanesien', ['Fidschi', 'Papua-Neuguinea', 'Salomonen', 'Vanuatu']],
          ['Mikronesien', ['Kiribati', 'Marshallinseln', 'Mikronesien, Föderierte Staaten von', 'Nauru', 'Palau']],
          ['Polynesien', ['Samoa', 'Tonga', 'Tuvalu']]
      ]],
      ['Sonstige', [
          ['Britische Überseegebiete', ['Britische Überseegebiete']],
          ['Unbekannt', ['Staatenlos', 'Ungeklärt / Ohne Angabe']]
      ]]
    ]
]
